### ISSUE TITLE
make sure regions_exclude is set in ec2.ini

### ISSUE THREAD

**Issue by gavD** [radify/radiian#56]
```
# AWS regions to make calls to. Set this to 'all' to make request to all regions
# in AWS and merge the results together. Alternatively, set this to a comma
# separated list of regions. E.g. 'us-east-1,us-west-1,us-west-2'
regions = us-east-1
# regions_exclude = us-gov-west-1,cn-north-1
```

Note that regions_exclude was commented out. Please make sure this is not commented out.

**Comment by jfmercer** [comment]
@gavD Would this mean that I need to add a new question about which region(s) to exclude? If not, could I simply leave it blank as `regions_exclude =`?

**Comment by gavD** [comment]
`ec2.ini` needs to have `regions_exclude = us-gov-west-1,cn-north-1` set as a default rather than just that line but commented out
