### ISSUE TITLE
Remove unused questions

### ISSUE THREAD

**Issue by gavD** [radify/radiian#73]
I don't think we need these questions:

* *What is your class instance tag?* - do we use this tag?
* *What tag name would you like for your old app?* - we should just use the default that radiian comes up with in all cases

See https://github.com/radify/radiian/pull/63 for reference - it never got merged but might be useful

**Comment by Jstillerman** [comment]
The class instance tag is used in immutable.yaml because the class of the new machine is called {{classname}}-immutable. Do we need to keep this?

**Comment by gavD** [comment]
good question. I say do this:

* Remove the tag in immutable.yaml
* Grep the project to make sure it's not used elsewhere
* Using the newest version of radiian including the changes made here, generate a new playbook to re-up your hello world application and **assert that** it all works correctly.
